services:
  app:
    build: .
    container_name: survey-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: survey_db
      JWT_SECRET: supersecretkey_1234567
      GOOGLE_CLIENT_ID: 232923029113-4qmipgl9dlonv1p6t7i0vbgu2l7j2cpn.apps.googleusercontent.com
      SUPABASE_URL: https://ejfdickbdcvgsgsawgvm.supabase.co
      SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqZmRpY2tiZGN2Z3Nnc2F3Z3ZtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODM3MDQyMiwiZXhwIjoyMDYzOTQ2NDIyfQ.XpZXj5AfTa_lON_lC5EHhiXN-fsIUgM-upMgA1_OqhA
    depends_on:
      db:
        condition: service_healthy
    networks:
      - survey-network

  db:
    image: postgres:15
    container_name: survey-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: survey_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d survey_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - survey-network

volumes:
  pgdata:

networks:
  survey-network:
    driver: bridge
